course/urls.py
## @brief urls for the course app.

from django.conf.urls import url, include
from django.contrib import admin
from . import views

## @brief url patterns for the course app.
urlpatterns = [
    url(r'^$', views.index),
    url(r'^(?P<course_id>[0-9]+)/detail/$', views.detail, name='detail'),
    url(r'^index/$', views.index, name='index'),
    url(r'^(?P<assignment_id>[0-9]+)/upload_submission/$', views.upload_submission, name='upload_submission'),
    url(r'^(?P<course_id>[0-9]+)/view_assignments/$', views.view_assignments, name='view_assignments'),
    url(r'^(?P<course_id>[0-9]+)/view_resources/$', views.view_resources, name='view_resources'),
]

onlineclassroom/urls.py
## @brief urls for the website.
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

## @brief url patterns for the website.
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login_user, name='login_user'),
    url(r'^register_user/$', views.register_user, name='register_user'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^course/', include(('course.urls', 'course'), namespace='course')),
    url(r'^instructor/', include(('instructor.urls', 'instructor'), namespace='instructor')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
## @brief Models for the course app.

from django.db import models
from django.contrib.auth.models import User
from instructor.models import Course
from django.urls import reverse


## @brief This class represents the students enrolled in the website.
class Student(models.Model):
    ## The user associated with the student
    user = models.ForeignKey(User,on_delete=None, default=1)

    ## The name of the student
    name = models.CharField(max_length=100)

    ## The roll number the student
    roll_no = models.CharField(max_length=100)

    ## The courses undertaken by the student
    course_list = models.ManyToManyField(Course)

    ## @brief This function returns the string representation of the student class.
    #
    # Used by Django admin website to represent the Student objects.
    # @param self The object pointer.
    def __str__(self):
        return self.name


## @brief This class represents the messages displayed in the forum.
class Message(models.Model):
    ## The content of message
    content = models.CharField(max_length=500)

    ## The course associated with the message
    course = models.ForeignKey(Course,default=1,on_delete=None)

    ## The sender of the message
    sender = models.ForeignKey(User,default=1, on_delete=None)

    ## The time when the message was posted
    time = models.CharField(max_length=100)


## @brief This class represents the notifications receieved by the students.
class Notification(models.Model):
    ## The content of notification
    content = models.CharField(max_length=500)

    ## The course associated with the notification
    course = models.ForeignKey(Course, default=1, on_delete=None)

    ## The time when the notification was posted/generated
    time = models.CharField(max_length=100)


## @brief This class represents the resources(lectures/study materials) for a course.
class Resources(models.Model):
    ## The resource file 
    file_resource = models.FileField(default='')

    ## The title for the resource
    title = models.CharField(max_length=100)

    ## The course associated with the resource
    course = models.ForeignKey(Course, default=1, on_delete=None)

course/forms.py
## @brief Forms for the course app.

from django import forms
from django.contrib.auth.models import User

from .models import Message
from instructor.models import Submission


## @brief This class represents the form to send a message in the forum.
class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ['content']


## @brief This class represents the form to add a submission for an assignment.
class SubmissionForm(forms.ModelForm):

    class Meta:
        model = Submission
        fields = ['file_submitted', 'feedback']

course/views.py
## @brief Views for the course app.

from django.contrib.auth.decorators import login_required
from .models import Student, Message, Notification, Resources
from instructor.models import Assignment, Course, Instructor
from django.shortcuts import render, redirect
from .forms import MessageForm, SubmissionForm
import datetime


## @brief view for the index page of the student.
#
# This view is called by /index url.\n
# It returns the student's homepage containing links to all the courses he is enrolled in and all the notifications.
@login_required
def index(request):
    student = Student.objects.get(user=request.user)
    courses = student.course_list.all()
    notifications = Notification.objects.filter(course__in=courses)
    return render(request, 'course/index.html', {'courses': courses, 'notifications': notifications})


## @brief view for the detail page of the course.
#
# This view is called by <course_id>/detail url.\n
# It returns the course's detail page containing forum and links to all the assignments and resources.
@login_required
def detail(request, course_id):
    user = request.user
    student = Student.objects.get(user=request.user)
    courses = student.course_list.all()
    course = Course.objects.get(id=course_id)
    instructor = course.instructor
    messages = Message.objects.filter(course=course)
    form = MessageForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            message = form.save(commit=False)
            message.course = course
            message.sender = user
            message.time = datetime.datetime.now().strftime('%H:%M, %d/%m/%y') # get the current date,time and convert into string
            message.save()
            try:
                student = Student.objects.get(user=request.user)
                return redirect('course:detail', course_id)

            except:
                return redirect('instructor:instructor_detail', course.id)

    else:
        form = MessageForm()

        context = {
            'course': course,
            'user': user,
            'instructor': instructor,
            'student': student,
            'courses': courses,
            'messages': messages,
            'form': form
        }

        return render(request, 'course/detail.html', context)


## @brief view for the assignments page of a course.
#
# This view is called by <course_id>/view_assignments url.\n
# It returns the webpage containing all the assignments of the course and links to download them and upload submissions.
@login_required
def view_assignments(request, course_id):
    course = Course.objects.get(id=course_id)
    assignments = Assignment.objects.filter(course=course)
    context = {
        'course' : course,
        'assignments' : assignments,
    }
    return render(request,'course/view_assignments.html',context)


## @brief view for the resources page of a course.
#
# This view is called by <course_id>/view_resources url.\n
# It returns the webpage containing all the resources of the course and links to download them.
@login_required
def view_resources(request, course_id):
    course = Course.objects.get(id=course_id)
    resources = Resources.objects.filter(course=course)
    context = {
        'course' : course,
        'resources' : resources,
    }
    return render(request,'course/view_resources.html',context)


## @brief view for the assignment's submission page.
#
# This view is called by <assignment_id>/upload_submission url.\n
# It returns the webpage containing a form to upload submission and redirects to the assignments page again after the form is submitted.
@login_required
def upload_submission(request, assignment_id):
    form = SubmissionForm(request.POST or None, request.FILES or None)
    assignment = Assignment.objects.get(id=assignment_id)
    course_id = assignment.course.id
    course = Course.objects.get(id=course_id)
    if form.is_valid():
        submission = form.save(commit=False)
        submission.user = request.user
        submission.assignment = assignment
        submission.time_submitted = datetime.datetime.now().strftime('%H:%M, %d/%m/%y')
        submission.save()
        return view_assignments(request, course_id)

    return render(request, 'course/upload_submission.html', {'form': form,'course': course})

course/templates/course/basic_page.html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Online Classroom Management System{% endblock %}</title>
        {% load staticfiles %}
        <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Abhaya Libre' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Alfa Slab One' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Ledger' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Volkhov' rel='stylesheet'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <style>
            a{
                color: yellow;
            }
            #id_content
            {
                width: 600px;
                height: 40px;
            }

            body
            {
                background: url('') no-repeat center center fixed;
                background-size: cover;
                font-family: Ledger;font-size: 20px;
            }
        </style>
    </head>
    <body background=""style="font-family: Ledger;font-size: 20px;">
    <nav class="navbar-fixed-top bg-primary">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                         <a class="navbar-brand" style="font-family:'Lobster',cursive;font-size:30px;" href="{% url 'course:index' %}">Online Classroom Management System</a>

            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </nav><br><br>
    {% block body %}
    {% endblock %}
    </body>

    <footer style="text-align:center;font-family:Lobster;">&copy; Copyright 2021 Online Classroom Management System</footer>



    </html>

course/templates/course/detail.html
{% extends 'course/basic_page.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}
{% block body %}
<br>
<div class="container-fluid songs-container">

    <div class="row">
        <!-- Left Album Info -->
        <div class="col-sm-6 col-md-3">
            <div class="panel panel-default">
                {% if course in courses %}
                <div class="panel-body" style="background-color: #e3f0e8;border: 0px solid #66cdaa;">
                    <a href="{% url 'course:detail' course.id %}">
                        {% if course.course_logo %}
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1 align="center">{{ course.code }}<br> <small>{{ course.name }}</small></h1>
                    <h2 align="center">{{ course.instructor }}</h2>
                </div>
            </div>
        </div>

        <div class="col-sm-9"style="color:white;">

            <div class="col-sm-2">
    <a href="{% url 'course:view_assignments' course.id %}">
        <button type="submit" class="btn btn-success"style="font-size: larger;padding-left: 20px;margin-left:150px">Assignments</button></a>
            </div>
            <div class="col-sm-4">

            </div>
            <div class="col-sm-2">
    <a href="{% url 'course:view_resources' course.id %}">
        <button type="submit" class="btn btn-success"style="font-size: larger;margin-left:0px">Resources</button></a>
            </div>

            <div class="col-sm-4"></div>
            <br><br><br>



            <div class="col-sm-10" style=" position:fixed-right;overflow-y: scroll; height:650px;border: 3px solid #66cdaa;background-color:#e3f0e8;color:black;font-family: 'Abhaya Libre';font-size:16px;">

                <h1 style="text-align:center;font-family:Volkhov,cursive;font-size:40px;color: #728892"> Forum </h1>


<!--
                <div class="col-sm-12" style="font-family: 'Alfa Slab One';font-size:24px;">
            <h3 align="center">Messages</h3>
                </div>
                -->
                <br>
                 <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{ field.errors }}</span>
                        </div>

                    <div class="col-sm-10" style="color: black;">{{ field }}
                    <button type="submit" style="margin-left:20px" class="btn btn-success">Send</button>
                    </div>
                    </div>
                    {% endfor %}


                </form>
    {% for message in messages reversed %}
        <br>
                <div style="background-color:#CDD8CD; border-radius:2%;padding:10px; margin:5px">
                    <b>{{ message.sender }}</b><br>
                    <div style="font-size:12px;">{{ message.time }}</div>
                    {{ message.content }}<br>
                </div>
    {% endfor %}
        </div><br><br><br>
        </div><br><br><br>
    </div><br><br><br>
</div>
{% else %}
    You are not enrolled in this course
{% endif %}
{% endblock %}

course/templates/course/index.html
{% extends 'course/basic_page.html' %}
{% block course_active %}active{% endblock %}


{% block body %}


<div class="albums-container container-fluid"style="font-family: Ledger;font-size: 22px;">

    <!-- Courses -->
    <div class="row col-sm-9" >
        <div class="col-sm-12"style="font-family: 'Alfa Slab One';font-size:24px;">
            <h3 align="center" style="font-family:Volkhov,cursive;font-size:40px;color: #728892">YOUR COURSES</h3>
        </div >
        {% if courses %}
            {% for course in courses %}
                <div  class="col-sm-6 col-lg-4" >
                    <div class="thumbnail" style="background-color: #e3f0e8;border: 0px solid #66cdaa;">
                        <a href="{% url 'course:detail' course.id %}">
                             <img src="{{ course.course_logo.url }}" class="img-responsive">
                            <!--{{ course.name }}-->
                        </a>

                        <div class="caption">
                            <h2>{{ course.code }}</h2>
                            <div style="height: 40px">
                                <h4>{{ course.name }}</h4>
                            </div>
                            <!-- View Details -->
                            <a href="{% url 'course:detail' course.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                        </div>

                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <h4>You are not enrolled in any courses</h4>
            </div>
        {% endif %}
    </div>
            <h3 align="center"style="position:fixed-right; top:2%; right:2%; font-family:Volkhov,cursive;font-size:30px;color: #728892">Notifications</h3>
    <div class="col-sm-3" style=" position:fixed-right;overflow-y: scroll; height:600px;border: 3px solid #66cdaa;background-color:#e3f0e8;color:black;font-family: 'Abhaya Libre';font-size:16px;">
        <div class="col-sm-10" style="font-family: 'Alfa Slab One';font-size:12px;">

        </div>

        {% for notification in notifications reversed %}

        <div style="background-color:#CDD8CD; border-radius:2%;padding:3px; margin:5px">
        <b>{{ notification.course }}</b><br>
        <div style="font-size:12px;">{{ notification.time }}</div>
        {{ notification.content }}
        </div>

{% endfor %}
    </div>

</div>


{% endblock %}

course/templates/course/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Testing successful!!</h2>
</body>
</html>

course/templates/course/upload_submission.html
{% extends 'course/basic_page.html' %}
{% block course_active %}active{% endblock %}

{% block body %}
<br>
<div class="container-fluid">


    <div class="row">

        <div class="col-sm-6 col-md-3">
            <div class="panel panel-default">

                <div class="panel-body" style="background-color: #e3f0e8;border: 0px solid #66cdaa;">
                    <a href="{% url 'course:detail' course.id %}">
                        {% if course.course_logo %}
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1 align="center">{{ course.code }}<br> <small>{{ course.name }}</small></h1>
                    <h2 align="center">{{ course.instructor }}</h2>
                </div>
            </div>
        </div>
        <br><br><br>
        <div class="col-sm-6">


                <div class="panel-body"style="background-color:#e3f0e8;color:black;border: 3px solid #66cdaa;font-family: 'Abhaya Libre';font-size:16px;">
                    <h3 align="center"; style="text-align:center;font-family:Volkhov,cursive;font-size:40px;color: #728892">Submit Assignment</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
               <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small">{{ field.errors }}</span>
            </div>
        <label class="control-label col-sm-5">{{ field.label_tag }}</label>
        <div class="col-sm-5">{{ field }}</div>
        </div>
        {% endfor %}

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
                </div>
            </div>



    </div>

</div>


{% endblock %}

course/templates/course/view_assignments.html
{% extends 'course/basic_page.html' %}
{% block course_active %}active{% endblock %}


{% block body %}
<br>
<div class="container-fluid songs-container" >

    <div class="row">

    <div class="col-sm-6 col-md-3">
            <div class="panel panel-default">

                <div class="panel-body" style="background-color: #e3f0e8;border: 0px solid #66cdaa;">
                    <a href="{% url 'course:detail' course.id %}">
                        {% if course.course_logo %}
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1 align="center">{{ course.code }}<br> <small>{{ course.name }}</small></h1>
                    <h2 align="center">{{ course.instructor }}</h2>
                </div>
            </div>
        </div>



        <div class="col-sm-7" style="align:center; overflow-y: scroll; height:650px;border: 3px solid #66cdaa;background-color:#e3f0e8;color:black;font-family: 'Abhaya Libre';font-size:16px;">
        <h3 align="center"; style="text-align:center;font-family:Volkhov,cursive;font-size:40px;color: #728892">Assignments</h3>
    {% for assignment in assignments reversed %}
<div style="background-color:#CDD8CD; border-radius:2%;padding:10px; margin:5px">
        {{ assignment.description }}<br>
        Post Time: {{ assignment.post_time }}<br>
        Deadline: {{ assignment.deadline }}<br><br>
        <a href="{{ assignment.file.url }}">
        <button type="submit" class="btn btn-success">Download Assignment</button></a>
        <a href="{% url 'course:upload_submission' assignment.id %}">
        <button type="submit" class="btn btn-success">Upload Submission</button></a>
        <br>
</div>
    {% endfor %}
        </div><br><br><br>
</div>
</div><br><br><br>
{% endblock %}

course/templates/course/view_resources.html
{% extends 'course/basic_page.html' %}
{% block course_active %}active{% endblock %}


{% block body %}
<br>
<div class="container-fluid songs-container">

    <div class="row">

    <div class="col-sm-6 col-md-3">
            <div class="panel panel-default">

                <div class="panel-body" style="background-color: #e3f0e8;border: 0px solid #66cdaa;">
                    <a href="{% url 'course:detail' course.id %}">
                        {% if course.course_logo %}
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1 align="center">{{ course.code }}<br> <small>{{ course.name }}</small></h1>
                    <h2 align="center">{{ course.instructor }}</h2>
                </div>
            </div>
        </div>



        <div class="col-sm-7" style="position:fixed-righ; overflow-y: scroll; height:650px;border: 3px solid #66cdaa;background-color:#e3f0e8;color:black;font-family: 'Abhaya Libre';font-size:16px;">
        <h3 align="center"; style="text-align:center;font-family:Volkhov,cursive;font-size:40px;color: #728892">Resources</h3>

    {% for resource in resources reversed %}
            <div style="background-color:#CDD8CD; border-radius:2%;padding:10px; margin:5px">
        {{ resource.title }} -
                <div style="position:right">
        <a href="{{ resource.file_resource.url }}" style="text-align:right">
            <button type="submit" class="btn btn-success">Download</button>
        </a><br>
                    </div>

            </div>
    {% endfor %}

        </div>
</div>
</div>
{% endblock %}