course/urls.py
## @brief urls for the course app.

from django.conf.urls import url, include
from django.contrib import admin
from . import views

## @brief url patterns for the course app.
urlpatterns = [
    url(r'^$', views.index),
    url(r'^(?P<course_id>[0-9]+)/detail/$', views.detail, name='detail'),
    url(r'^index/$', views.index, name='index'),
    url(r'^(?P<assignment_id>[0-9]+)/upload_submission/$', views.upload_submission, name='upload_submission'),
    url(r'^(?P<course_id>[0-9]+)/view_assignments/$', views.view_assignments, name='view_assignments'),
    url(r'^(?P<course_id>[0-9]+)/view_resources/$', views.view_resources, name='view_resources'),
]

instructor/urls.py
## @brief urls for the instructor app.

from django.conf.urls import url, include
from django.contrib import admin
from . import views

## @brief url patterns for the instructor app.
urlpatterns = [
    url(r'^instructor_index/$', views.instructor_index, name='instructor_index'),
    url(r'^(?P<course_id>[0-9]+)/instructor_detail/$', views.instructor_detail, name='instructor_detail'),
    url(r'^(?P<course_id>[0-9]+)/add_assignment/$', views.add_assignment, name='add_assignment'),
    url(r'^(?P<course_id>[0-9]+)/add_resource/$', views.add_resource, name='add_resource'),
    url(r'^(?P<course_id>[0-9]+)/add_notification/$', views.add_notification, name='add_notification'),
    url(r'^(?P<course_id>[0-9]+)/view_all_assignments/$', views.view_all_assignments, name='view_all_assignments'),
    url(r'^(?P<assignment_id>[0-9]+)/view_all_submissions/$', views.view_all_submissions, name='view_all_submissions'),
    url(r'^(?P<assignment_id>[0-9]+)/view_feedback/$', views.view_feedback, name='view_feedback'),
]

onlineclassroom/urls.py
## @brief urls for the website.
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

## @brief url patterns for the website.
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login_user, name='login_user'),
    url(r'^register_user/$', views.register_user, name='register_user'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^course/', include(('course.urls', 'course'), namespace='course')),
    url(r'^instructor/', include(('instructor.urls', 'instructor'), namespace='instructor')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
## @brief Models for the course app.

from django.db import models
from django.contrib.auth.models import User
from instructor.models import Course
from django.urls import reverse


## @brief This class represents the students enrolled in the website.
class Student(models.Model):
    ## The user associated with the student
    user = models.ForeignKey(User,on_delete=None, default=1)

    ## The name of the student
    name = models.CharField(max_length=100)

    ## The roll number the student
    roll_no = models.CharField(max_length=100)

    ## The courses undertaken by the student
    course_list = models.ManyToManyField(Course)

    ## @brief This function returns the string representation of the student class.
    #
    # Used by Django admin website to represent the Student objects.
    # @param self The object pointer.
    def __str__(self):
        return self.name


## @brief This class represents the messages displayed in the forum.
class Message(models.Model):
    ## The content of message
    content = models.CharField(max_length=500)

    ## The course associated with the message
    course = models.ForeignKey(Course,default=1,on_delete=None)

    ## The sender of the message
    sender = models.ForeignKey(User,default=1, on_delete=None)

    ## The time when the message was posted
    time = models.CharField(max_length=100)


## @brief This class represents the notifications receieved by the students.
class Notification(models.Model):
    ## The content of notification
    content = models.CharField(max_length=500)

    ## The course associated with the notification
    course = models.ForeignKey(Course, default=1, on_delete=None)

    ## The time when the notification was posted/generated
    time = models.CharField(max_length=100)


## @brief This class represents the resources(lectures/study materials) for a course.
class Resources(models.Model):
    ## The resource file 
    file_resource = models.FileField(default='')

    ## The title for the resource
    title = models.CharField(max_length=100)

    ## The course associated with the resource
    course = models.ForeignKey(Course, default=1, on_delete=None)

instructor/models.py
## @brief Models for the instructor app.

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


## @brief This class represents the instructors enrolled in the website.
class Instructor(models.Model):
    ## The user associated with the instructor
    user = models.ForeignKey(User,on_delete=models.CASCADE, default=1)

    ## The name of the instructor
    name = models.CharField(max_length=100)

    ## The information about the instructor
    information = models.CharField(max_length=1000,default=1)

    ## @brief This function returns the string representation of the instructor class.
    #
    # Used by Django admin website to represent the instructor objects.
    # @param self The object pointer.
    def __str__(self):
        return self.name


## @brief This class represents the courses.
class Course(models.Model):
    ## The name of the course
    name = models.CharField(max_length=100)

    ## The course code
    code = models.CharField(max_length=100)

    ## The instructor of the course
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)

    ## The course logo
    course_logo = models.FileField(default=1)

    ## @brief This function returns the string representation of the course class.
    #
    # Used by Django admin website to represent the course objects.
    def __str__(self):
        return self.name


## @brief This class represents the assignments in a course.
class Assignment(models.Model):
    ## The description of the assignment
    description = models.CharField(max_length=1000, default='')

    ## The file containing the problems for the assignment
    file = models.FileField(default='')

    ## The course associated with the assignment
    course = models.ForeignKey(Course,on_delete=models.CASCADE)

    ## The date,time of posting the assignment
    post_time = models.CharField(max_length=100)

    ## The deadline to complete the assignment for the students
    deadline = models.CharField(max_length=100)


## @brief This class represents the submissions for an assignment.
class Submission(models.Model):
    ## The file submitted by student
    file_submitted = models.FileField(default='')

    ## The date,time of uploading the submission
    time_submitted = models.CharField(max_length=100)

    ## The user associated with the submission(who uploaded the submission)
    user = models.ForeignKey(User,on_delete=models.CASCADE, default=1)

    ## The assignment associated with the submission
    assignment = models.ForeignKey(Assignment,on_delete=models.CASCADE, default=1)

    ## @var The list of integer choices available to give feedback for the assignment for which the submission is uploaded
    CHOICES = [(i+1, i+1) for i in range(10)]

    ## The feedback given to the assignment by the student while uploading the submission
    feedback = models.IntegerField(choices=CHOICES)

instructor/forms.py
## @brief Forms for the course app.

from django import forms
from django.contrib.auth.models import User

from .models import Assignment
from course.models import Notification, Resources

## @brief This class represents the form to add a notification.
class NotificationForm(forms.ModelForm):

    class Meta:
        model = Notification
        fields = ['content']


## @brief This class represents the form to add an assignment.
class AssignmentForm(forms.ModelForm):

    class Meta:
        model = Assignment
        fields = ['description', 'file', 'deadline']


## @brief This class represents the form to add a resource.
class ResourceForm(forms.ModelForm):

    class Meta:
        model = Resources
        fields = ['title', 'file_resource']

instructor/views.py
## @brief Views for the instructor app.

from django.contrib.auth.decorators import login_required
from .models import Instructor, Submission, Assignment
from course.models import Course, Message, Notification, Student
from django.shortcuts import render, HttpResponse, redirect
from .forms import AssignmentForm, NotificationForm, ResourceForm
from course.forms import MessageForm
import datetime


## @brief view for the index page of the instructor.
#
# This view is called by /instructor_index url.\n
# It returns the instructor's homepage containing links to all the courses he teaches.
@login_required
def instructor_index(request):
    user = request.user
    instructor = Instructor.objects.get(user=request.user)
    courses = Course.objects.filter(instructor=instructor)
    context = {
        'user': user,
        'instructor': instructor,
        'courses': courses,
    }
    return render(request, 'instructor/instructor_index.html', context)


## @brief view for the detail page of the course.
#
# This view is called by <course_id>/instructor_detail url.\n
# It returns the course's detail page containing forum and links to add assignment,resource,notifications
# and view all the assignments and their submissions.
@login_required
def instructor_detail(request, course_id):
    user = request.user
    instructor = Instructor.objects.get(user=request.user)
    courses = Course.objects.filter(instructor=instructor)
    course = Course.objects.get(id=course_id)
    messages = Message.objects.filter(course=course)
    form = MessageForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            message = form.save(commit=False)
            message.course = course
            message.sender = user
            message.time = datetime.datetime.now().strftime('%H:%M, %d/%m/%y')
            message.save()
            try:
                student = Student.objects.get(user=request.user)
                return redirect('course:detail', course_id)

            except:
                return redirect('instructor:instructor_detail', course.id)

    else:
        form = MessageForm()

        context = {
                'user': user,
                'instructor': instructor,
                'course': course,
                'courses': courses,
                'messages': messages,
                'form' : form
            }

        return render(request, 'instructor/instructor_detail.html', context)


## @brief view for the course's add-notification page
#
# This view is called by <course_id>/add_notification url.\n
# It returns the webpage containing a form to add notification and redirects to the course's detail page again after the form is submitted.
@login_required
def add_notification(request, course_id):
    form = NotificationForm(request.POST or None)
    course = Course.objects.get(id=course_id)
    if form.is_valid():
        notification = form.save(commit=False)
        notification.course = course
        notification.time = datetime.datetime.now().strftime('%H:%M, %d/%m/%y') # get the current date,time and convert into string
        notification.save()
        return redirect('instructor:instructor_detail', course.id)

    return render(request, 'instructor/add_notification.html', {'course': course, 'form': form})


## @brief view for the course's add-assignment page.
#
# This view is called by <course_id>/add_assignment url.\n
# It returns the webpage containing a form to add an assignment and redirects to the course's detail page again after the form is submitted.
@login_required
def add_assignment(request, course_id):
    form = AssignmentForm(request.POST or None, request.FILES or None)
    course = Course.objects.get(id=course_id)
    if form.is_valid():
        assignment = form.save(commit=False)
        assignment.file = request.FILES['file']
        assignment.post_time = datetime.datetime.now().strftime('%H:%M, %d/%m/%y')
        assignment.course = course
        assignment.save()
        notification = Notification()
        notification.content = "New Assignment Uploaded"
        notification.course = course
        notification.time = datetime.datetime.now().strftime('%H:%M, %d/%m/%y')
        notification.save()
        return redirect('instructor:instructor_detail', course.id)

    return render(request, 'instructor/create_assignment.html', {'form': form, 'course': course})


## @brief view for the course's add-resource page.
#
# This view is called by <course_id>/add_resource url.\n
# It returns the webpage containing a form to add a resource and redirects to the course's detail page again after the form is submitted.
@login_required
def add_resource(request, course_id):
    form = ResourceForm(request.POST or None, request.FILES or None)
    instructor = Instructor.objects.get(user=request.user)
    course = Course.objects.get(id=course_id)
    if form.is_valid():
        resource = form.save(commit=False)
        resource.file_resource = request.FILES['file_resource']
        resource.course = course
        resource.save()
        notification = Notification()
        notification.content = "New Resource Added - " + resource.title
        notification.course = course
        notification.time = datetime.datetime.now().strftime('%H:%M, %d/%m/%y')
        notification.save()
        return redirect('instructor:instructor_detail', course.id)

    return render(request, 'instructor/add_resource.html', {'form': form, 'course': course})


## @brief view for the assignments page of a course.
#
# This view is called by <course_id>/view_all_assignments url.\n
# It returns the webpage containing all the assignments of the course and links to their submissions and feedbacks given by the students.
@login_required
def view_all_assignments(request, course_id):
    course = Course.objects.get(id=course_id)
    assignments = Assignment.objects.filter(course=course)
    return render(request, 'instructor/view_all_assignments.html', {'assignments' : assignments,'course': course})


## @brief view for the submissions page of an assignment.
#
# This view is called by <assignment_id>/view_all_submissions url.\n
# It returns the webpage containing links to all the submissions of an assignment.
@login_required
def view_all_submissions(request,assignment_id):
    assignment = Assignment.objects.get(id=assignment_id)
    submissions = Submission.objects.filter(assignment=assignment)
    course = assignment.course
    return render(request, 'instructor/view_all_submissions.html', {'submissions' : submissions,'course': course})


## @brief view for the feedback page containing an histogram of all the feddbacks provided by the students.
#
# This view is called by <assignment_id>/view_feedback url.\n
# It returns a webpage containing the feedback received by the students organized in the form of histogram.
@login_required
def view_feedback(request,assignment_id):
    import matplotlib.pyplot as plt
    import numpy as np
    from matplotlib.backends.backend_agg import FigureCanvasAgg
    import matplotlib.ticker as ticker

    assignment = Assignment.objects.get(id=assignment_id)
    submissions = Submission.objects.filter(assignment=assignment)

    feedbacks1 = list(map(lambda x: x.feedback, submissions)) #extract the feedbacks from the submissions list
    feedbacks = np.array(feedbacks1)

    fig = plt.figure(figsize=(10,6))
    fig.suptitle('Feedback received from the students', fontsize=16, fontweight='bold')
    fig.subplots_adjust(bottom=0.3)
    ax = fig.add_subplot(111)

    ax.set_xlabel('Rating(out of 10)')
    ax.set_ylabel('Number of Students')
    x = feedbacks
    ax.hist(x, bins=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], fc='lightblue', alpha=1, align='left', edgecolor='black', linewidth=1.0)
    ax.set_xticks([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
    ax.yaxis.set_major_locator(ticker.MultipleLocator(1)) #sets the difference between adjacent y-tics

    plt.figtext(0.2, 0.1, 'Average Rating : '+ str(round(np.mean(feedbacks),2)),
                bbox={'facecolor': 'lightblue', 'alpha': 0.5, 'pad': 10})     #adds box in graph to display mean rating
    plt.figtext(0.5, 0.1, 'Number of Students Students who rated : ' + str(len(feedbacks1)),
                bbox={'facecolor': 'lightblue', 'alpha': 0.5, 'pad': 10})     #adds box in graph to display number of students who rated

    canvas = FigureCanvasAgg(fig)
    response = HttpResponse(content_type='image/png')
    canvas.print_png(response)  # converts the figure to http response
    return response

instructor/templates/instructor/add_notification.html
{% extends 'instructor/instructor_basic_page.html' %}
{% block course_active %}active{% endblock %}

{% block body %}
<br>
<div class="container-fluid">


    <div class="row">

        <div class="col-sm-6 col-md-3">
            <div class="panel panel-default">

                <div class="panel-body" style="background-color: #e3f0e8;border: 0px solid #66cdaa;">
                    <a href="{% url 'instructor:instructor_detail' course.id %}">
                        {% if course.course_logo %}
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1 align="center">{{ course.code }}<br> <small>{{ course.name }}</small></h1>
                    <h2 align="center">{{ course.instructor }}</h2>
                </div>
            </div>
        </div>

        <br><br><br>
        <div class="col-sm-7">


                <div class="panel-body"style="background-color:#e3f0e8;color:black;border: 3px solid #66cdaa;font-family: 'Abhaya Libre';font-size:16px;">
                    <h3 align="center"; style="text-align:center;font-family:Volkhov,cursive;font-size:40px;color: #728892">Add Notification</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
               <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small">{{ field.errors }}</span>
            </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-5">{{ field }}</div>
        </div>
        {% endfor %}

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
                </div>
            </div>



    </div>

</div>


{% endblock %}

instructor/templates/instructor/add_resource.html
{% extends 'instructor/instructor_basic_page.html' %}
{% block course_active %}active{% endblock %}

{% block body %}
<br>
<div class="container-fluid">


    <div class="row">

        <div class="col-sm-6 col-md-3">
            <div class="panel panel-default">

                <div class="panel-body" style="background-color: #e3f0e8;border: 0px solid #66cdaa;">
                    <a href="{% url 'instructor:instructor_detail' course.id %}">
                        {% if course.course_logo %}
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1 align="center">{{ course.code }}<br> <small>{{ course.name }}</small></h1>
                    <h2 align="center">{{ course.instructor }}</h2>
                </div>
            </div>
        </div>

        <br><br><br>
        <div class="col-sm-6">


                <div class="panel-body"style="background-color:#e3f0e8;color:black;border: 3px solid #66cdaa;font-family: 'Abhaya Libre';font-size:16px;">
                    <h3 align="center"; style="text-align:center;font-family:Volkhov,cursive;font-size:40px;color: #728892">Add Resource</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
               <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small">{{ field.errors }}</span>
            </div>
        <label class="control-label col-sm-5">{{ field.label_tag }}</label>
        <div class="col-sm-5">{{ field }}</div>
        </div>
        {% endfor %}

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
                </div>
            </div>



    </div>

</div>


{% endblock %}

instructor/templates/instructor/instructor_basic_page.html
  <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Online CLassroom Management System{% endblock %}</title>
        {% load staticfiles %}
        <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Abhaya Libre' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Alfa Slab One' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Ledger' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Volkhov' rel='stylesheet'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <style>
            a{
                color: yellow;
            }
            #id_content
            {
                width: 600px;
                height: 40px;
            }

            body
            {
                background: url('https://i.pinimg.com/originals/5d/5d/79/5d5d79ab40f17440b11dfdf9cd0f1f08.jpg') no-repeat center center fixed;
                background-size: cover;
                font-family: Ledger;font-size: 20px;
            }
        </style>
    </head>
    <body background=""style="font-family: Ledger;font-size: 20px;">
    <nav class="navbar-fixed-top bg-primary">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                         <a class="navbar-brand" style="font-family:'Lobster',cursive;font-size:30px;" href="{% url 'instructor:instructor_index' %}">Online CLassroom Management System</a>

            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </nav><br><br>
    {% block body %}
    {% endblock %}
    </body>
 
    </html>

instructor/templates/instructor/instructor_detail.html
{% extends 'instructor/instructor_basic_page.html' %}
{% block title %}{{ course }}{% endblock %}
{% block albums_active %}active{% endblock %}
{% block body %}
<br>
<div class="container-fluid songs-container">

    <div class="row">
        <!-- Left Album Info -->
        <div class="col-sm-6 col-md-3">
            <div class="panel panel-default">
                {% if course in courses %}
                <div class="panel-body" style="background-color: #e3f0e8;border: 0px solid #66cdaa;">
                    <a href="{% url 'instructor:instructor_detail' course.id %}">
                        {% if course.course_logo %}
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1 align="center">{{ course.code }}<br> <small>{{ course.name }}</small></h1>
                    <h2 align="center">{{ course.instructor }}</h2>
                </div>
            </div>
        </div>

        <div class="col-sm-9"style="color:white;">

            <div class="col-sm-2">
    <a href="{% url 'instructor:add_assignment' course.id %}">
        <button type="submit" class="btn btn-success"style="font-size: larger;padding-left: 20px;margin-left:0px">Add assignment</button></a>
            </div>


            <div class="col-sm-2">
    <a href="{% url 'instructor:view_all_assignments' course.id %}">
        <button type="submit" class="btn btn-success"style="font-size: larger;margin-left:60px">Submissions</button></a>
            </div>



            <div class="col-sm-2">
    <a href="{% url 'instructor:add_resource' course.id %}">
        <button type="submit" class="btn btn-success"style="font-size: larger;margin-left:67px">Add a resource</button></a>
            </div>


            <div class="col-sm-2">
    <a href="{% url 'instructor:add_notification' course.id %}">
        <button type="submit" class="btn btn-success"style="font-size: larger;margin-left:106px">Notify Students</button></a>
            </div>


            <div class="col-sm-4"></div>
            <br><br><br>



            <div class="col-sm-10" style=" position:fixed-right;overflow-y: scroll; height:650px;border: 3px solid #66cdaa;background-color:#e3f0e8;color:black;font-family: 'Abhaya Libre';font-size:16px;">

                <h1 style="text-align:center;font-family:Volkhov,cursive;font-size:40px;color: #728892"> Forum </h1>


<!--
                <div class="col-sm-12" style="font-family: 'Alfa Slab One';font-size:24px;">
            <h3 align="center">Messages</h3>
                </div>
                -->
                <br>
                 <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="course" value="{{ course }}">

                    {% for field in form %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{ field.errors }}</span>
                        </div>

                    <div class="col-sm-10" style="color: black;">{{ field }}
                    <button type="submit" style="margin-left:20px" class="btn btn-success">Send</button>
                    </div>
                    </div>
                    {% endfor %}


                </form>
    {% for message in messages reversed %}
        <br>
                <div style="background-color:#CDD8CD; border-radius:2%;padding:10px; margin:5px">
                    <b>{{ message.sender }}</b><br>
                    <div style="font-size:12px;">{{ message.time }}</div>
                    {{ message.content }}<br>
                </div>
    {% endfor %}
        </div><br><br><br>
        </div><br><br><br>
    </div><br><br><br>
</div>
{% else %}
    You are not enrolled in this course
{% endif %}
{% endblock %}

<!--


    <h2>You have arrived at your course homepage!</h2><br><br>
    <a href="{% url 'instructor:add_assignment' course.id %}">Add an assignment</a><br>
    <a href="{% url 'instructor:view_all_assignments' course.id %}">View Submissions</a><br>
    <a href="{% url 'instructor:add_resource' course.id %}">Add a resource</a><br>
    <h3> Forum </h3>
    <a href="{% url 'course:create_message' course.id %}">Write a message</a>
    <a href="{% url 'instructor:add_notification' course.id %}">Add a notification</a>

    {% for message in messages %}
        {{ message.sender }}<br>
        {{ message.time }}<br>
        {{ message.content }}<br><br>
    {% endfor %}


-->

instructor/templates/instructor/view_all_assignments.html
{% extends 'instructor/instructor_basic_page.html' %}
{% block course_active %}active{% endblock %}

{% block body %}
<br>
<div class="container-fluid songs-container">

    <div class="row">
        <!-- Left Album Info -->
        <div class="col-sm-6 col-md-3">
            <div class="panel panel-default">

                <div class="panel-body" style="background-color: #e3f0e8;border: 0px solid #66cdaa;">
                    <a href="{% url 'instructor:instructor_detail' course.id %}">
                        {% if course.course_logo %}
                            <img src="{{ course.course_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1 align="center">{{ course.code }}<br> <small>{{ course.name }}</small></h1>
                    <h2 align="center">{{ course.instructor }}</h2>
                </div>
            </div>
        </div>



        <div class="col-sm-7" style="align:center; overflow-y: scroll; height:650px;border: 3px solid #66cdaa;background-color:#e3f0e8;color:black;font-family: 'Abhaya Libre';font-size:16px;">
        <h3 align="center"; style="text-align:center;font-family:Volkhov,cursive;font-size:40px;color: #728892">Assignments</h3>
    {% for assignment in assignments reversed %}
            <div style="background-color:#CDD8CD; border-radius:2%;padding:10px; margin:5px">
            {{ assignment.description }}<br>
            Deadline : {{ assignment.deadline }}<br>
    <a href="{% url 'instructor:view_all_submissions' assignment.id %}">
        <button type="submit" class="btn btn-success">Submissions</button>
    </a>
    <a href="{% url 'instructor:view_feedback' assignment.id %}">
        <button type="submit" class="btn btn-success">Feedback</button>
    </a><br>
            </div>
    {% endfor %}
        </div>

</div>
{% endblock %}